project_id = "jltipylfxmthuxsybltt"

[functions.generate-ad]
verify_jwt = false

[functions.boost-ad]
verify_jwt = false

[functions.zenix-ai-admin]
verify_jwt = false

[functions.auto-boost-runner]
verify_jwt = false

[functions.admin-delete-user]
verify_jwt = false

[functions.generate-video]
verify_jwt = false
