/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AppPlansRouteImport } from './routes/app.plans'
import { Route as AppCreateRouteImport } from './routes/app.create'
import { Route as AppAutoBoostRouteImport } from './routes/app.auto-boost'
import { Route as AppAdsRouteImport } from './routes/app.ads'
import { Route as AppAccountRouteImport } from './routes/app.account'
import { Route as AdminZenixAiRouteImport } from './routes/admin.zenix-ai'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminPromotionsRouteImport } from './routes/admin.promotions'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminAdsRouteImport } from './routes/admin.ads'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AppPlansRoute = AppPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AppRoute,
} as any)
const AppCreateRoute = AppCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppRoute,
} as any)
const AppAutoBoostRoute = AppAutoBoostRouteImport.update({
  id: '/auto-boost',
  path: '/auto-boost',
  getParentRoute: () => AppRoute,
} as any)
const AppAdsRoute = AppAdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AdminZenixAiRoute = AdminZenixAiRouteImport.update({
  id: '/zenix-ai',
  path: '/zenix-ai',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPromotionsRoute = AdminPromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdsRoute = AdminAdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/zenix-ai': typeof AdminZenixAiRoute
  '/app/account': typeof AppAccountRoute
  '/app/ads': typeof AppAdsRoute
  '/app/auto-boost': typeof AppAutoBoostRoute
  '/app/create': typeof AppCreateRoute
  '/app/plans': typeof AppPlansRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/zenix-ai': typeof AdminZenixAiRoute
  '/app/account': typeof AppAccountRoute
  '/app/ads': typeof AppAdsRoute
  '/app/auto-boost': typeof AppAutoBoostRoute
  '/app/create': typeof AppCreateRoute
  '/app/plans': typeof AppPlansRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/zenix-ai': typeof AdminZenixAiRoute
  '/app/account': typeof AppAccountRoute
  '/app/ads': typeof AppAdsRoute
  '/app/auto-boost': typeof AppAutoBoostRoute
  '/app/create': typeof AppCreateRoute
  '/app/plans': typeof AppPlansRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/admin/ads'
    | '/admin/payments'
    | '/admin/promotions'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/zenix-ai'
    | '/app/account'
    | '/app/ads'
    | '/app/auto-boost'
    | '/app/create'
    | '/app/plans'
    | '/admin/'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin/ads'
    | '/admin/payments'
    | '/admin/promotions'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/zenix-ai'
    | '/app/account'
    | '/app/ads'
    | '/app/auto-boost'
    | '/app/create'
    | '/app/plans'
    | '/admin'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/admin/ads'
    | '/admin/payments'
    | '/admin/promotions'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/zenix-ai'
    | '/app/account'
    | '/app/ads'
    | '/app/auto-boost'
    | '/app/create'
    | '/app/plans'
    | '/admin/'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/plans': {
      id: '/app/plans'
      path: '/plans'
      fullPath: '/app/plans'
      preLoaderRoute: typeof AppPlansRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/create': {
      id: '/app/create'
      path: '/create'
      fullPath: '/app/create'
      preLoaderRoute: typeof AppCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/auto-boost': {
      id: '/app/auto-boost'
      path: '/auto-boost'
      fullPath: '/app/auto-boost'
      preLoaderRoute: typeof AppAutoBoostRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ads': {
      id: '/app/ads'
      path: '/ads'
      fullPath: '/app/ads'
      preLoaderRoute: typeof AppAdsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/account': {
      id: '/app/account'
      path: '/account'
      fullPath: '/app/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/zenix-ai': {
      id: '/admin/zenix-ai'
      path: '/zenix-ai'
      fullPath: '/admin/zenix-ai'
      preLoaderRoute: typeof AdminZenixAiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/promotions': {
      id: '/admin/promotions'
      path: '/promotions'
      fullPath: '/admin/promotions'
      preLoaderRoute: typeof AdminPromotionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ads': {
      id: '/admin/ads'
      path: '/ads'
      fullPath: '/admin/ads'
      preLoaderRoute: typeof AdminAdsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdsRoute: typeof AdminAdsRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminPromotionsRoute: typeof AdminPromotionsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminZenixAiRoute: typeof AdminZenixAiRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdsRoute: AdminAdsRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminPromotionsRoute: AdminPromotionsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminZenixAiRoute: AdminZenixAiRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppAdsRoute: typeof AppAdsRoute
  AppAutoBoostRoute: typeof AppAutoBoostRoute
  AppCreateRoute: typeof AppCreateRoute
  AppPlansRoute: typeof AppPlansRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppAdsRoute: AppAdsRoute,
  AppAutoBoostRoute: AppAutoBoostRoute,
  AppCreateRoute: AppCreateRoute,
  AppPlansRoute: AppPlansRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
